export const audioFiles = {
	C4: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/C4.mp3',
	'C#4 / Db4': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/C%234%3ADb4.mp3',
	D4: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/D4.mp3',
	'D#4 / Eb4': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/D%234%3AEb4.mp3',
	E4: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/E4.mp3',
	F4: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/F4.mp3',
	'F#4 / Gb4': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/F%234%3AGb4.mp3',
	G4: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/G4.mp3',
	'G#4 / Ab4': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/G%234%3AAb4.mp3',
	A4: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/A4.mp3',
	'A#4 / Bb4': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/A%234%3ABb4.mp3',
	B4: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/B4.mp3',
	C5: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/C5.mp3',
	'C#5 / Db5': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/C%235%3ADb5.mp3',
	D5: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/D5.mp3',
	'D#5 / Eb5': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/D%235%3AEb5.mp3',
	E5: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/E5.mp3',
	F5: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/F5.mp3',
	'F#5 / Gb5': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/F%235%3AGb5.mp3',
	G5: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/G5.mp3',
	'G#5 / Ab5': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/G%235%3AAb5.mp3',
	A5: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/A5.mp3',
	'A#5 / Bb5': 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/A%235%3ABb5.mp3',
	B5: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/B5.mp3',
	C6: 'https://notemaster.s3.us-west-1.amazonaws.com/noteMasterAudio/C6.mp3',
};
